CREATE USER BDY1102_P1 IDENTIFIED BY "Codigo.practica_1"
DEFAULT TABLESPACE "DATA"
TEMPORARY TABLESPACE "TEMP";
ALTER USER BDY1102_P1 QUOTA UNLIMITED ON DATA;
GRANT CREATE SESSION TO BDY1102_P1;
GRANT "RESOURCE" TO BDY1102_P1;
ALTER USER BDY1102_P1 DEFAULT ROLE "RESOURCE";
